# Author: Cameron F. Abrams, <cfa22@drexel.edu>
import yaml
import os
from collections import UserList
import pandas as pd
import logging

logger = logging.getLogger(__name__)

class AnswerSet:
    _keys = ['label', 'value', 'units', 'formatter']
    def __init__(self, serial: int = 0):
        self.serial = serial
        self.dumpname = f'answers-{serial:08d}.yaml'
        self.D = {}

    @classmethod
    def from_yaml(cls, filename, delete=False):
        """
        Create an AnswerSet instance by loading from a YAML file of the same format as that 
        generated by the to_yaml() method.
        """
        root, ext = os.path.splitext(filename)
        assert ext in ['.yaml', '.yml'], f'{filename} does not end in .yaml or .yml'
        tokens = root.split('-')
        assert len(tokens) == 2, f'{filename} should be of the format "answers-<serial#>.yaml"'
        serial = int(tokens[1])
        R = cls(serial)
        with open(filename, 'r') as f:
            R.D = yaml.safe_load(f)
        if delete:
            os.remove(filename)
        return R
    
    def register(self, index, label=None, value=None, units=None, formatter=None, group=None):
        """
        Register an answer entry for a particular question index.
        """
        if not index in self.D:
            self.D[index] = []
        # if value is a numpy data type, convert to native python type
        if hasattr(value, 'item'):
            value = value.item()
        self.D[index].append(dict(  label=label,
                                    value=value,
                                    units=units,
                                    formatter=formatter,
                                    group=group))
    
    def display(self, index, element=0):
        D = None
        if element < len(self.D[index]):
            D = self.D[index][element]
        if D:
            fmt = D.get('formatter',None)
            val = D.get('value',None)
            label = D.get('label',None)
            units = D.get('units',None)
            vstr = ''
            if val:
                if fmt:
                    vstr = fmt.format(val)
                else:
                    vstr = str(val)
                if units:
                    vstr += f' {units}'
            if label:
                if vstr:
                    return f'{label} = {vstr}'
                else:
                    return label
        return ''

    def to_yaml(self):
        with open(self.dumpname, 'w') as f:
            yaml.safe_dump(self.D, f)

class AnswerSuperSet(UserList):

    def __init__(self, files=[], delete=False):
        data=[]
        for f in files:
            data.append(AnswerSet.from_yaml(f, delete=delete))
        super().__init__(data)
        if not self._check_congruency():
            print(f'Error: There is a lack of congruency among {files}')
        self._make_dfs()

    def to_latex(self):
        result = ''
        for group_name, group_data in self.groups.items():
            df = group_data['df']
            formatters = group_data.get('formatters', None)
            result += df.to_latex(formatters=formatters, index=False, longtable=True)#,header=self.headings)
        return result
    
    def _check_congruency(self):
        if len(self)>0:
            indices=list(self.data[0].D.keys())
            for l in self.data[1:]:
                test_indices=list(l.D.keys())
                check=all([x==y for x,y in zip(indices,test_indices)])
                if not check:
                    return False
            for i in indices:
                ilen=len(self.data[0].D[i])
                for l in self.data[1:]:
                    test_ilen=len(l.D[i])
                    check=ilen==test_ilen
                    if not check:
                        return False
        return True
    
    def _make_dfs(self):
        # to do: groupify
        serials = [x.serial for x in self.data]
        # logger.debug(serials)
        # self.headings = ['serials']
        # keys = ['serials']
        values = {'serials': serials}
        pattern = self.data[0]  # keys in first AnswerSet form the pattern all sets follow
        self.formatters = {}
        self.groups = {}
        for index, AL in pattern.D.items():
            for a in AL:
                key = f'{index}-{a["label"]}'
                group = a.get('group', None)
                if group:
                    if group not in self.groups:
                        self.groups[group] = dict(formatters={}, df=None, values={'serials': serials})
                    self.groups[group]['values'][key] = []
                    if 'formatter' in a:
                        self.groups[group]['formatters'][key] = a['formatter']
                else:
                    values[key] = []
                    if 'formatter' in a:
                        self.formatters[key] = a['formatter']
        # logger.debug(values)
        for inst in self.data:
            for index, AL in inst.D.items():
                for a in AL:
                    key = f'{index}-{a["label"]}'
                    group = a.get('group', None)
                    if group:
                        self.groups[group]['values'][key].append(a['value'])
                    else:
                        values[key].append(a['value'])
        # logger.debug(values)
        if not self.groups:
            DF = pd.DataFrame(values)
            DF.sort_values(by='serials', inplace=True)
            self.groups['base'] = dict(formatters=self.formatters, df=DF)
        else:
            for gname, gdata in self.groups.items():
                DF = pd.DataFrame(gdata['values'])
                DF.sort_values(by='serials', inplace=True)
                self.groups[gname]['df'] = DF
        # print(self.DF)


